### ISSUE TITLE
the problems of ESD

### ISSUE THREAD

**Issue by goodbai2** [jefferyYu/UMT#9]
Hey,i am attracted to the code of your paper,and would like to ask how the 'ESD Module' and 'Conversion Matrix' are implemented in the paper? which part of the code it correspond to?Look forward to your reply.

**Comment by jefferyYu** [comment]
Hi there,

Both the ESD module and the conversion matrix are implemented in the "MTCCMBertForMMTokenClassificationCRF" class in "mner_modeling.py", and you can refer to the code. Besides, the initialization of the conversion matrix is in line 620-633 of the "run_mtmner_crf.py" file. For these detailed questions, I am sorry that I may not have time to reply again due to my busy schedule.

Best,
Jianfei
